---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Here are some plots
Today we are making interactive plots in plotly. We will make examples using the NYC airbnb dataset.

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Do some initial data cleaning / subsetting
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location/2) %>% 
  select(
    rating, neighbourhood_group, neighbourhood, 
    room_type, lat, long, price) %>% 
  drop_na(rating) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  )
```

Use plotly to make some quick plots.
```{r}
nyc_airbnb %>% 
  mutate(
    text_label = 
      str_c("Price: ", price, "\nNeighborhood: ", neighbourhood)) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
  
  
  
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```


Next up box plot

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )
```

Lets do a bar chart with number of rentals

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~n,
    type = "bar"
  )
```

```{r}
plot_ly(
  z= volcano, type = "heatmap"
)
```

chloropleth
```{r eval=FALSE, include=FALSE}
plot_ly(
  type = "choropleth",
  location = c("AZ", "CA", "VT"),
  locationmode - "USA_states",
  colorscale = "Viridis",
  z = c(10, 20, 40)) %>% 
  layout (geo = list(scope="usa"))

```

